name: "Deploy to BigQuery"
on:
  push:
    branches: ["main"]

jobs:
  deploy_schemas:
    runs-on: ubuntu-latest
    name: Deploy to BigQuery
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Deploy schemas to BigQuery
        uses: jashparekh/bigquery-action@v3
        env:
          gcp_project: 'nais-analyse-dev-8caa'
          dataset_schema_directory: 'views'
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}